import React from "react";
import { Dimensions } from "react-native";
import { StyleSheet, View, SafeAreaView } from "react-native";
import WebView from "react-native-webview";

const { width, height } = Dimensions.get("window");

const iFrameStyle = `
        <style>
          html {
            overflow-y: hidden;
            overflow-x: hidden;
            height: 100%;
          }
          body {
            background-color: black;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
          }
        </style>
      `;
export const buildHTML = (source) => `
      <!DOCTYPE html>
      <html>
        <head>
          ${iFrameStyle}
          <meta name="viewport" content="initial-scale=1">
        </head>
        <div style="padding-bottom: 177.78%; max-width: 100%; position: relative;"><iframe src="https://www.youtube.com/embed?listType=playlist&list=${source}&autoplay=1&loop=1&modestbranding=1&rel=0&iv_load_policy=3&controls=0&disablekb=1&fs=0" width=${width} height=${height} style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;" frameborder="0"></iframe></div>
        <!--Youtube Embed Code Generated by https://www.onetools.me/-->      </html>
      `;

const YoutubePlayer = ({ source }) => {
  return (
    <SafeAreaView>
      <View style={styles.videoContainer}>
        <WebView
          source={{ html: buildHTML(source) }}
          allowsFullscreenVideo={false}
          allowsInlineMediaPlayback
        />
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
  },
  videoContainer: {
    height: height,
  },
});

export default YoutubePlayer;
